# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mbirdie <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/07 17:35:47 by mbirdie           #+#    #+#              #
#    Updated: 2019/09/07 17:42:18 by mbirdie          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
all:
	gcc -Wall -Wextra -Werror -o $(NAME) ft_display_file.c
clean:
	/bin/rm -f *.o
fclean: clean
	/bin/rm -f $(NAME)
re: fclean all
